/**
 * Pre-defined watchlists matching Moneycontrol / NSE official index constituents.
 * Symbols are NSE tickers (no .NS suffix).
 * Lists are based on the most recent NSE semi-annual review.
 */

export type WatchlistKey = "NIFTY100" | "NIFTYMIDCAP100" | "NIFTYSMALLCAP100";

export interface WatchlistMeta {
  key: WatchlistKey;
  label: string;
  description: string;
}

export const WATCHLIST_META: Record<WatchlistKey, WatchlistMeta> = {
  NIFTY100: {
    key: "NIFTY100",
    label: "Nifty 100",
    description: "Top 100 large-cap stocks (Nifty 50 + Nifty Next 50) by full market cap.",
  },
  NIFTYMIDCAP100: {
    key: "NIFTYMIDCAP100",
    label: "Nifty Midcap 100",
    description: "100 mid-cap stocks ranked 101-250 by full market cap.",
  },
  NIFTYSMALLCAP100: {
    key: "NIFTYSMALLCAP100",
    label: "Nifty Smallcap 100",
    description: "100 small-cap stocks ranked 251-500 by full market cap.",
  },
};

/** Nifty 50 + Nifty Next 50 = Nifty 100 */
export const NIFTY100_SYMBOLS: string[] = [
  // Nifty 50
  "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","HINDUNILVR","ITC","SBIN","BHARTIARTL","KOTAKBANK",
  "LT","HCLTECH","ASIANPAINT","AXISBANK","MARUTI","SUNPHARMA","TITAN","BAJFINANCE","NTPC","ULTRACEMCO",
  "WIPRO","NESTLEIND","M&M","POWERGRID","TATASTEEL","TECHM","JSWSTEEL","INDUSINDBK","BAJAJFINSV","HDFCLIFE",
  "DRREDDY","CIPLA","COALINDIA","BPCL","HEROMOTOCO","TATAMOTORS","DIVISLAB","BRITANNIA","SHRIRAMFIN","SBILIFE",
  "EICHERMOT","ONGC","GRASIM","BAJAJ-AUTO","ADANIPORTS","ADANIENT","HINDALCO","APOLLOHOSP","TATACONSUM","LTIM",
  // Nifty Next 50
  "ABB","ADANIGREEN","ADANIPOWER","AMBUJACEM","DMART","BAJAJHLDNG","BANKBARODA","BERGEPAINT","BEL","BOSCHLTD",
  "CANBK","CHOLAFIN","COLPAL","DABUR","DLF","GAIL","GODREJCP","HAVELLS","ICICIGI","ICICIPRULI",
  "IOC","INDIGO","IRFC","JINDALSTEL","LICI","MARICO","MOTHERSON","NAUKRI","PIDILITIND","PFC",
  "PNB","RECLTD","SIEMENS","SRF","TATAPOWER","TORNTPHARM","TRENT","TVSMOTOR","VBL","VEDL",
  "ZOMATO","ZYDUSLIFE","HAL","JIOFIN","ADANIENSOL","JSWENERGY","UNITDSPR","CGPOWER","PERSISTENT","INDUSTOWER",
];

/** Nifty Midcap 100 — official NSE constituents */
export const NIFTYMIDCAP100_SYMBOLS: string[] = [
  "ABCAPITAL","ABFRL","ACC","AIAENG","ALKEM","ASHOKLEY","ASTRAL","AUBANK","AUROPHARMA","BALKRISIND",
  "BANDHANBNK","BANKINDIA","BHARATFORG","BHEL","BIOCON","COFORGE","COLPAL","CONCOR","CUMMINSIND","DALBHARAT",
  "DEEPAKNTR","DELHIVERY","DIXON","ESCORTS","EXIDEIND","FEDERALBNK","FLUOROCHEM","FORTIS","GMRINFRA","GODREJPROP",
  "GUJGASLTD","HDFCAMC","HINDPETRO","HONAUT","IDFCFIRSTB","IDEA","IGL","INDHOTEL","IPCALAB","JUBLFOOD",
  "KPITTECH","L&TFH","LICHSGFIN","LUPIN","M&MFIN","MAXHEALTH","MAZDOCK","MFSL","MOTILALOFS","MPHASIS",
  "MRF","MUTHOOTFIN","NHPC","NMDC","NYKAA","OBEROIRLTY","OFSS","OIL","PAGEIND","PATANJALI",
  "PAYTM","PEL","PETRONET","PHOENIXLTD","PIIND","POLICYBZR","POLYCAB","POONAWALLA","PRESTIGE","RVNL",
  "SAIL","SOLARINDS","SONACOMS","STARHEALTH","SUNDARMFIN","SUNTV","SUPREMEIND","SYNGENE","TATACOMM","TATAELXSI",
  "TATATECH","THERMAX","TIINDIA","TORNTPOWER","TUBEINVEST","UBL","UNIONBANK","UPL","VOLTAS","YESBANK",
  "MANKIND","JSL","NLCINDIA","KEI","HUDCO","ABBOTINDIA","GLAND","LODHA","CRISIL","KALYANKJIL",
];

/** Nifty Smallcap 100 — official NSE constituents */
export const NIFTYSMALLCAP100_SYMBOLS: string[] = [
  "AARTIIND","ANGELONE","APARINDS","APLAPOLLO","ASTERDM","ATGL","ATUL","BIKAJI","BLUESTARCO","BSE",
  "BALRAMCHIN","BLS","BSOFT","CAMS","CASTROLIND","CDSL","CEATLTD","CENTRALBK","CESC","CHAMBLFERT",
  "CHENNPETRO","CGCL","CRAFTSMAN","CYIENT","DOMS","ELECTCAST","EIDPARRY","ENGINERSIN","EPL","ERIS",
  "FINCABLES","FINPIPE","FIVESTAR","FSL","GESHIP","GICRE","GILLETTE","GLENMARK","GNFC","GODFRYPHLP",
  "GPPL","GRSE","GSPL","HBLPOWER","HFCL","HSCL","IDBI","IEX","INTELLECT","IOB",
  "IRCON","JBCHEPHARM","JBMA","JKCEMENT","JMFINANCIL","JUSTDIAL","JYOTHYLAB","KAJARIACER","KARURVYSYA","KEC",
  "KFINTECH","KIRLOSBROS","KIRLOSENG","KPRMILL","LATENTVIEW","LAURUSLABS","LXCHEM","MASTEK","MCX","METROBRAND",
  "MGL","MMTC","NATCOPHARM","NATIONALUM","NBCC","NCC","NHIMHIM","NSLNISP","OLECTRA","PCBL",
  "PGHL","PNBHOUSING","PRINCEPIPE","PVRINOX","RADICO","RBLBANK","REDINGTON","ROUTE","SCI","SCHAEFFLER",
  "SHYAMMETL","SOBHA","STARCEMENT","SWANENERGY","SYRMA","TANLA","TATAINVEST","TBOTEK","TEJASNET","TRIDENT",
];

/** Lookup display name from UNIVERSE_RAW; falls back to symbol if not present. */
const NAMES: Record<string, string> = {
  // Spot-fix friendly display names for common symbols not in core UNIVERSE.
  "M&M": "Mahindra & Mahindra",
  "BAJAJ-AUTO": "Bajaj Auto",
  "L&TFH": "L&T Finance",
  "M&MFIN": "M&M Financial Services",
  "ICICIGI": "ICICI Lombard General Insurance",
  "ICICIPRULI": "ICICI Prudential Life",
  "LICI": "Life Insurance Corporation of India",
  "JIOFIN": "Jio Financial Services",
  "ADANIENSOL": "Adani Energy Solutions",
  "ADANIENT": "Adani Enterprises",
  "ADANIPORTS": "Adani Ports & SEZ",
  "ADANIGREEN": "Adani Green Energy",
  "ADANIPOWER": "Adani Power",
  "ATGL": "Adani Total Gas",
  "DMART": "Avenue Supermarts (DMart)",
  "NAUKRI": "Info Edge (Naukri)",
  "PFC": "Power Finance Corp",
  "RECLTD": "REC Limited",
  "PNB": "Punjab National Bank",
  "BANKBARODA": "Bank of Baroda",
  "CANBK": "Canara Bank",
  "SAIL": "Steel Authority of India",
  "BHEL": "Bharat Heavy Electricals",
  "GAIL": "GAIL India",
  "IOC": "Indian Oil Corp",
  "HINDPETRO": "Hindustan Petroleum",
  "BPCL": "Bharat Petroleum",
  "ONGC": "Oil & Natural Gas Corp",
  "IGL": "Indraprastha Gas",
  "MGL": "Mahanagar Gas",
  "GUJGASLTD": "Gujarat Gas",
  "HUDCO": "Housing & Urban Development",
  "IRFC": "Indian Railway Finance Corp",
  "IRCON": "Ircon International",
  "RVNL": "Rail Vikas Nigam",
  "CONCOR": "Container Corp of India",
  "MAZDOCK": "Mazagon Dock Shipbuilders",
  "GRSE": "Garden Reach Shipbuilders",
  "BEL": "Bharat Electronics",
  "HAL": "Hindustan Aeronautics",
  "SOLARINDS": "Solar Industries",
  "CGPOWER": "CG Power & Industrial Solutions",
  "POLYCAB": "Polycab India",
  "HAVELLS": "Havells India",
  "VBL": "Varun Beverages",
  "UNITDSPR": "United Spirits",
  "UBL": "United Breweries",
  "MARICO": "Marico",
  "DABUR": "Dabur India",
  "GODREJCP": "Godrej Consumer Products",
  "COLPAL": "Colgate-Palmolive India",
  "PIDILITIND": "Pidilite Industries",
  "BERGEPAINT": "Berger Paints",
  "AMBUJACEM": "Ambuja Cements",
  "DALBHARAT": "Dalmia Bharat",
  "JKCEMENT": "JK Cement",
  "ACC": "ACC Limited",
  "STARCEMENT": "Star Cement",
  "ABCAPITAL": "Aditya Birla Capital",
  "ABFRL": "Aditya Birla Fashion & Retail",
  "BAJAJHLDNG": "Bajaj Holdings & Investment",
  "INDUSTOWER": "Indus Towers",
  "IDEA": "Vodafone Idea",
  "POLICYBZR": "PB Fintech (Policybazaar)",
  "PAYTM": "One 97 Communications (Paytm)",
  "ZOMATO": "Zomato (Eternal)",
  "NYKAA": "FSN E-Commerce (Nykaa)",
  "DELHIVERY": "Delhivery",
  "TATATECH": "Tata Technologies",
  "TATACOMM": "Tata Communications",
  "TATAELXSI": "Tata Elxsi",
  "TATAINVEST": "Tata Investment Corp",
  "TATAPOWER": "Tata Power",
  "ABB": "ABB India",
  "SIEMENS": "Siemens India",
  "CUMMINSIND": "Cummins India",
  "BHARATFORG": "Bharat Forge",
  "ASHOKLEY": "Ashok Leyland",
  "ESCORTS": "Escorts Kubota",
  "EXIDEIND": "Exide Industries",
  "BALKRISIND": "Balkrishna Industries",
  "BOSCHLTD": "Bosch Limited",
  "MOTHERSON": "Samvardhana Motherson",
  "MRF": "MRF Limited",
  "TIINDIA": "Tube Investments of India",
  "TUBEINVEST": "Tube Investments of India",
  "SONACOMS": "Sona BLW Precision Forgings",
  "DIXON": "Dixon Technologies",
  "KPITTECH": "KPIT Technologies",
  "PERSISTENT": "Persistent Systems",
  "COFORGE": "Coforge",
  "MPHASIS": "Mphasis",
  "OFSS": "Oracle Financial Services",
  "TATAELSXI": "Tata Elxsi",
  "INDIGO": "InterGlobe Aviation (IndiGo)",
  "INDHOTEL": "Indian Hotels Co",
  "TRENT": "Trent (Tata Group)",
  "PAGEIND": "Page Industries",
  "JUBLFOOD": "Jubilant FoodWorks",
  "BIKAJI": "Bikaji Foods",
  "VOLTAS": "Voltas",
  "BLUESTARCO": "Blue Star",
  "WHIRLPOOL": "Whirlpool of India",
  "CROMPTON": "Crompton Greaves Consumer",
  "FORTIS": "Fortis Healthcare",
  "MAXHEALTH": "Max Healthcare",
  "ASTERDM": "Aster DM Healthcare",
  "GLAND": "Gland Pharma",
  "ABBOTINDIA": "Abbott India",
  "MANKIND": "Mankind Pharma",
  "ZYDUSLIFE": "Zydus Lifesciences",
  "TORNTPHARM": "Torrent Pharmaceuticals",
  "TORNTPOWER": "Torrent Power",
  "AUROPHARMA": "Aurobindo Pharma",
  "BIOCON": "Biocon",
  "LUPIN": "Lupin",
  "ALKEM": "Alkem Laboratories",
  "IPCALAB": "Ipca Laboratories",
  "GLENMARK": "Glenmark Pharmaceuticals",
  "LAURUSLABS": "Laurus Labs",
  "JBCHEPHARM": "JB Chemicals & Pharma",
  "ERIS": "Eris Lifesciences",
  "NATCOPHARM": "Natco Pharma",
  "SYNGENE": "Syngene International",
  "PEL": "Piramal Enterprises",
  "PIIND": "PI Industries",
  "DEEPAKNTR": "Deepak Nitrite",
  "FLUOROCHEM": "Gujarat Fluorochemicals",
  "SRF": "SRF Limited",
  "ATUL": "Atul Limited",
  "AARTIIND": "Aarti Industries",
  "GNFC": "Gujarat Narmada Valley Fert",
  "CHAMBLFERT": "Chambal Fertilisers",
  "EIDPARRY": "EID Parry (India)",
  "BALRAMCHIN": "Balrampur Chini Mills",
  "TRIDENT": "Trident Limited",
  "KPRMILL": "KPR Mill",
  "PGHL": "Procter & Gamble Health",
  "GILLETTE": "Gillette India",
  "RADICO": "Radico Khaitan",
  "JYOTHYLAB": "Jyothy Labs",
  "VEDL": "Vedanta",
  "JINDALSTEL": "Jindal Steel & Power",
  "JSL": "Jindal Stainless",
  "JSWENERGY": "JSW Energy",
  "NHPC": "NHPC Limited",
  "NLCINDIA": "NLC India",
  "SJVN": "SJVN Limited",
  "OIL": "Oil India",
  "PETRONET": "Petronet LNG",
  "GSPL": "Gujarat State Petronet",
  "NMDC": "NMDC Limited",
  "NATIONALUM": "National Aluminium (NALCO)",
  "HINDCOPPER": "Hindustan Copper",
  "RATNAMANI": "Ratnamani Metals & Tubes",
  "APLAPOLLO": "APL Apollo Tubes",
  "WELCORP": "Welspun Corp",
  "WELSPUNIND": "Welspun India",
  "DLF": "DLF Limited",
  "GODREJPROP": "Godrej Properties",
  "OBEROIRLTY": "Oberoi Realty",
  "PRESTIGE": "Prestige Estates",
  "BRIGADE": "Brigade Enterprises",
  "PHOENIXLTD": "Phoenix Mills",
  "LODHA": "Macrotech Developers (Lodha)",
  "SOBHA": "Sobha Limited",
  "FEDERALBNK": "Federal Bank",
  "IDFCFIRSTB": "IDFC First Bank",
  "BANDHANBNK": "Bandhan Bank",
  "KARURVYSYA": "Karur Vysya Bank",
  "RBLBANK": "RBL Bank",
  "YESBANK": "Yes Bank",
  "AUBANK": "AU Small Finance Bank",
  "BANKINDIA": "Bank of India",
  "UNIONBANK": "Union Bank of India",
  "CENTRALBK": "Central Bank of India",
  "IOB": "Indian Overseas Bank",
  "IDBI": "IDBI Bank",
  "PNBHOUSING": "PNB Housing Finance",
  "LICHSGFIN": "LIC Housing Finance",
  "MUTHOOTFIN": "Muthoot Finance",
  "MFSL": "Max Financial Services",
  "POONAWALLA": "Poonawalla Fincorp",
  "STARHEALTH": "Star Health Insurance",
  "MOTILALOFS": "Motilal Oswal Financial",
  "ANGELONE": "Angel One",
  "JMFINANCIL": "JM Financial",
  "CAMS": "Computer Age Management Services",
  "KFINTECH": "KFin Technologies",
  "BSE": "BSE Limited",
  "MCX": "Multi Commodity Exchange",
  "CDSL": "Central Depository Services",
  "IEX": "Indian Energy Exchange",
  "GICRE": "General Insurance Corp",
  "CRISIL": "CRISIL Limited",
  "GMRINFRA": "GMR Infrastructure",
  "NBCC": "NBCC India",
  "NCC": "NCC Limited",
  "KEC": "KEC International",
  "HFCL": "HFCL Limited",
  "HBLPOWER": "HBL Power Systems",
  "TANLA": "Tanla Platforms",
  "MASTEK": "Mastek Limited",
  "INTELLECT": "Intellect Design Arena",
  "BSOFT": "BirlaSoft",
  "CYIENT": "Cyient",
  "LATENTVIEW": "Latent View Analytics",
  "JUSTDIAL": "Just Dial",
  "ROUTE": "Route Mobile",
  "TBOTEK": "TBO Tek",
  "TEJASNET": "Tejas Networks",
  "FSL": "Firstsource Solutions",
  "ELECTCAST": "Electrosteel Castings",
  "JBMA": "JBM Auto",
  "CRAFTSMAN": "Craftsman Automation",
  "SCHAEFFLER": "Schaeffler India",
  "CEATLTD": "CEAT Limited",
  "CASTROLIND": "Castrol India",
  "SCI": "Shipping Corp of India",
  "GESHIP": "Great Eastern Shipping",
  "CHENNPETRO": "Chennai Petroleum Corp",
  "GPPL": "Gujarat Pipavav Port",
  "EPL": "EPL Limited",
  "FINPIPE": "Finolex Industries",
  "FINCABLES": "Finolex Cables",
  "PRINCEPIPE": "Prince Pipes & Fittings",
  "SUPREMEIND": "Supreme Industries",
  "ASTRAL": "Astral Limited",
  "KAJARIACER": "Kajaria Ceramics",
  "BLS": "BLS International",
  "DOMS": "DOMS Industries",
  "FIVESTAR": "Five-Star Business Finance",
  "CGCL": "Capri Global Capital",
  "REDINGTON": "Redington",
  "OLECTRA": "Olectra Greentech",
  "MMTC": "MMTC Limited",
  "PCBL": "PCB Limited",
  "SHYAMMETL": "Shyam Metalics",
  "SUNDARMFIN": "Sundaram Finance",
  "TIINDIA2": "Tube Investments of India",
  "PVRINOX": "PVR Inox",
  "SUNTV": "Sun TV Network",
  "SWANENERGY": "Swan Energy",
  "GODFRYPHLP": "Godfrey Phillips India",
  "METROBRAND": "Metro Brands",
  "KALYANKJIL": "Kalyan Jewellers",
  "KEI": "KEI Industries",
  "THERMAX": "Thermax",
  "SYRMA": "Syrma SGS Technology",
  "AIAENG": "AIA Engineering",
  "NHIMHIM": "NHIM Industries",
  "NSLNISP": "NSLNISP",
  "HSCL": "Himadri Speciality Chemical",
  "LXCHEM": "Laxmi Organic Industries",
  "HONAUT": "Honeywell Automation",
  "KIRLOSBROS": "Kirloskar Brothers",
  "KIRLOSENG": "Kirloskar Oil Engines",
  "HDFCAMC": "HDFC Asset Management",
};

export function watchlistName(symbol: string): string {
  return NAMES[symbol] ?? symbol;
}

export function getWatchlistSymbols(key: WatchlistKey): string[] {
  switch (key) {
    case "NIFTY100": return NIFTY100_SYMBOLS;
    case "NIFTYMIDCAP100": return NIFTYMIDCAP100_SYMBOLS;
    case "NIFTYSMALLCAP100": return NIFTYSMALLCAP100_SYMBOLS;
  }
}
